services:
  mysql_ctn_final:
    build:
      context: .
      dockerfile: Dockerfile.final_db
    container_name: mysql_ctn_final
    environment:
      MYSQL_ROOT_PASSWORD: 6equj5_root
      MYSQL_DATABASE: home_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 6equj5_db_user
    volumes:
      - mysql_vol_2:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - app_net_2

  # Below container runs the frontend application at localhost:3000

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   container_name: frontend
  #   environment:
  #     VITE_API_BASE_URL: http://localhost:3100
  #   ports:
  #     - 3000:3000

  # Below container runs the backend application at localhost:3100

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    environment:
      PORT: 3100
      DB_USER_NAME: db_user
      DB_NAME: home_db
      DB_USER_PASSWORD: 6equj5_db_user
      DB_PORT: 3306
      DB_HOST: mysql_ctn_final
    ports:
      - 3100:3100
    networks:
      - app_net_2

networks:
  app_net_2:

volumes:
  mysql_vol_2:
